// Generated by gencpp from file ROS_ESSENTIALS_CPP/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_ESSENTIALS_CPP_MESSAGE_ADDTWOINTS_H
#define ROS_ESSENTIALS_CPP_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ROS_ESSENTIALS_CPP/AddTwoIntsRequest.h>
#include <ROS_ESSENTIALS_CPP/AddTwoIntsResponse.h>


namespace ROS_ESSENTIALS_CPP
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ROS_ESSENTIALS_CPP


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ROS_ESSENTIALS_CPP::AddTwoInts > {
  static const char* value()
  {
    return "ROS_ESSENTIALS_CPP/AddTwoInts";
  }

  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoInts >
template<>
struct MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoInts >::value();
  }
  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest> should match
// service_traits::DataType< ::ROS_ESSENTIALS_CPP::AddTwoInts >
template<>
struct DataType< ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ROS_ESSENTIALS_CPP::AddTwoInts >::value();
  }
  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoInts >
template<>
struct MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_ESSENTIALS_CPP::AddTwoInts >::value();
  }
  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse> should match
// service_traits::DataType< ::ROS_ESSENTIALS_CPP::AddTwoInts >
template<>
struct DataType< ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ROS_ESSENTIALS_CPP::AddTwoInts >::value();
  }
  static const char* value(const ::ROS_ESSENTIALS_CPP::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_ESSENTIALS_CPP_MESSAGE_ADDTWOINTS_H
