// Generated by gencpp from file ros_service_assignment/RectangleAreaServiceResponse.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREASERVICERESPONSE_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREASERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service_assignment
{
template <class ContainerAllocator>
struct RectangleAreaServiceResponse_
{
  typedef RectangleAreaServiceResponse_<ContainerAllocator> Type;

  RectangleAreaServiceResponse_()
    : are(0.0)  {
    }
  RectangleAreaServiceResponse_(const ContainerAllocator& _alloc)
    : are(0.0)  {
  (void)_alloc;
    }



   typedef float _are_type;
  _are_type are;





  typedef boost::shared_ptr< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaServiceResponse_

typedef ::ros_service_assignment::RectangleAreaServiceResponse_<std::allocator<void> > RectangleAreaServiceResponse;

typedef boost::shared_ptr< ::ros_service_assignment::RectangleAreaServiceResponse > RectangleAreaServiceResponsePtr;
typedef boost::shared_ptr< ::ros_service_assignment::RectangleAreaServiceResponse const> RectangleAreaServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator1> & lhs, const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.are == rhs.are;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator1> & lhs, const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_service_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb368af2fec583ff0b854074a57dc2b9";
  }

  static const char* value(const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb368af2fec583ffULL;
  static const uint64_t static_value2 = 0x0b854074a57dc2b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service_assignment/RectangleAreaServiceResponse";
  }

  static const char* value(const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 are\n"
"\n"
;
  }

  static const char* value(const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.are);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service_assignment::RectangleAreaServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "are: ";
    Printer<float>::stream(s, indent + "  ", v.are);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAREASERVICERESPONSE_H
