// Generated by gencpp from file ros_service_assignment/RectangleAeraServiceRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICEREQUEST_H
#define ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service_assignment
{
template <class ContainerAllocator>
struct RectangleAeraServiceRequest_
{
  typedef RectangleAeraServiceRequest_<ContainerAllocator> Type;

  RectangleAeraServiceRequest_()
    : wid(0.0)
    , hei(0.0)  {
    }
  RectangleAeraServiceRequest_(const ContainerAllocator& _alloc)
    : wid(0.0)
    , hei(0.0)  {
  (void)_alloc;
    }



   typedef float _wid_type;
  _wid_type wid;

   typedef float _hei_type;
  _hei_type hei;





  typedef boost::shared_ptr< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAeraServiceRequest_

typedef ::ros_service_assignment::RectangleAeraServiceRequest_<std::allocator<void> > RectangleAeraServiceRequest;

typedef boost::shared_ptr< ::ros_service_assignment::RectangleAeraServiceRequest > RectangleAeraServiceRequestPtr;
typedef boost::shared_ptr< ::ros_service_assignment::RectangleAeraServiceRequest const> RectangleAeraServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator1> & lhs, const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.wid == rhs.wid &&
    lhs.hei == rhs.hei;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator1> & lhs, const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_service_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "957a18c93f443cf4bf16478586ae9da8";
  }

  static const char* value(const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x957a18c93f443cf4ULL;
  static const uint64_t static_value2 = 0xbf16478586ae9da8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service_assignment/RectangleAeraServiceRequest";
  }

  static const char* value(const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 wid\n"
"float32 hei\n"
;
  }

  static const char* value(const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wid);
      stream.next(m.hei);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAeraServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service_assignment::RectangleAeraServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "wid: ";
    Printer<float>::stream(s, indent + "  ", v.wid);
    s << indent << "hei: ";
    Printer<float>::stream(s, indent + "  ", v.hei);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_ASSIGNMENT_MESSAGE_RECTANGLEAERASERVICEREQUEST_H
